SELECT CODE.DATE_COMMANDE, CODE.DATE_ENVOI, CODE.LIVREE, CODE.ACQUITEE, CODE.ANNULEE, DEDE.QUANTITE, DEDE.PORT, DEDE.REMISE, DEDE.RETOURNE, DEDE.ECHANGE, PRIT.REF_PRODUIT, PRIT.NO_FOURNISSEUR, PRIT.QUANTITE AS PRODUITS_QUANTITE, CAIE.NOM_CATEGORIE, CAIE.DESCRIPTION FROM COMMANDES CODE
INNER JOIN DETAILS_COMMANDES DEDE ON DEDE.NO_COMMANDE = CODE.NO_COMMANDE
INNER JOIN PRODUITS PRIT ON PRIT.REF_PRODUIT = DEDE.REF_PRODUIT
INNER JOIN CATEGORIES CAIE ON CAIE.CODE_CATEGORIE = PRIT.CODE_CATEGORIE